# codesigning_identity: "Apple Distribution: Aleksandr Potemkin (74739P8ZK8)" will find when creating match repo with command  fastlane match appstore


fastlane_version "2.98.0"
default_platform :ios

platform :ios do
  before_all do |lane, options|
	ENV["XCODE_PROJ"] = "./ios/#{ENV['APP_SCHEMA_NAME']}.xcodeproj"
	ENV["PLIST"] = "./#{ENV['APP_SCHEMA_NAME']}/Info.plist"
	ENV["APP_NAME"] = ENV['APP_SCHEMA_NAME']
	ENV["FASTLANE_PASSWORD"] = ENV["GIT_PASS"]
  end

	lane :everything do
		setup
		compile
		deploy
	end

  lane :setup do
	setup_project
  end

  lane :compile do
	build
  end

  lane :deploy do
    	deploy_gym
  end


  private_lane :setup_project do
	create_keychain(
		name: "#{ENV['APP_SCHEMA_NAME']}_keychain",
		password: ENV['APP_SCHEMA_NAME'],
		default_keychain: true,
		unlock: true,
	    timeout: 3600,
		lock_when_sleeps: false
	)
  end

  private_lane :build do
   disable_automatic_code_signing(path: "ios/#{ENV['APP_SCHEMA_NAME']}.xcodeproj",
    team_id: ENV['TEAM_ID']
   )

	match(
		type: "appstore",
		readonly: true,
        keychain_name: "#{ENV['APP_SCHEMA_NAME']}_keychain",
        keychain_password: ENV['APP_SCHEMA_NAME']
  	)
  	update_project_provisioning(
      xcodeproj: ENV["XCODE_PROJ"],
      profile: ENV["sigh_#{ENV['APP_ID']}_appstore_profile-path"],
      target_filter: ENV['APP_SCHEMA_NAME'],
      build_configuration: "Release",
      code_signing_identity: ENV['CODE_SIGN_ID']
    )
  end

  private_lane :deploy_gym do
      gym(
        scheme: ENV['APP_SCHEMA_NAME'],
        workspace: "ios/#{ENV['APP_SCHEMA_NAME']}.xcworkspace",
        export_method: "app-store",
        clean: true,
        export_method: "app-store",
        output_directory:"./build",
        configuration: "Release",
        export_options: {
           method: "app-store",
           provisioningProfiles: {
             ENV["APP_ID"] => ENV["sigh_#{ENV['APP_ID']}_appstore_profile-name"]
           }
        },
        codesigning_identity: ENV['CODE_SIGN_ID']
      )
      enable_automatic_code_signing(path: "ios/#{ENV['APP_SCHEMA_NAME']}.xcodeproj")
    end

end
