fastlane_version "2.98.0"
default_platform :ios

platform :ios do
  before_all do |lane, options|
	ENV["XCODE_PROJ"] = "./ios/begun.xcodeproj"
	ENV["APP_ID"] = "mobi.robofruit.run-tracking-app"
	ENV["PLIST"] = "./begun/Info.plist"
	ENV["APP_NAME"] = "begun"
	ENV["FASTLANE_PASSWORD"] = "Vlad009277"
  end

	lane :everything do
		setup
		compile
		deploy
	end

  lane :setup do
	setup_project
  end

  lane :compile do
	build
  end

  lane :deploy do
    	deploy_gym
  end


  private_lane :setup_project do
	create_keychain(
		name: "begun_keychain",
		password: "begun",
		default_keychain: true,
		unlock: true,
	    timeout: 3600,
		lock_when_sleeps: false
	)
  end

  private_lane :build do
   #disable_automatic_code_signing(path: "ios/begun.xcodeproj")

	match(
		type: "appstore",
		readonly: true,
        keychain_name: "begun_keychain",
        keychain_password: "begun"
  	)
  	update_project_provisioning(
      xcodeproj: ENV["XCODE_PROJ"],
      profile: ENV["sigh_mobi.robofruit.run-tracking-app_appstore_profile-path"],
      target_filter: "begun",
      build_configuration: "Release",
      code_signing_identity: "iPhone Developer: VLADIMIR GRIGORYAN."
    )
  end

  private_lane :deploy_gym do
      gym(
        scheme: "begun",
        workspace: "ios/begun.xcworkspace",
        export_method: "app-store",
        clean: true,
        export_method: "app-store",
        output_directory:"./build",
        configuration: "Release",
        export_options: {
           method: "app-store",
           provisioningProfiles: {
             ENV["APP_ID"] => ENV["sigh_mobi.robofruit.run-tracking-app_appstore_profile-name"]
           }
        },
        codesigning_identity: "iPhone Developer: VLADIMIR GRIGORYAN."
      )
      enable_automatic_code_signing(path: "ios/begun.xcodeproj")
    end

end
